language: node_js

services:
  - docker

jobs:
  include:
    - stage: deploy
      install:
      - docker build -t ikethecoder/git-sae-ops .
      provider: script
      script: bash docker_push || travis_terminate 1
      on:
        all_branches: true
        condition: "$TRAVIS_BRANCH =~ ^master|develop$ || -n $TRAVIS_TAG"  